# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4bf158b1540d5f4cf90fff4e783205c33abac1f122f8b7c39c971b6f030acff6772e27a88efb36b975aba929a8a56ec424dc2cf5bf02e8ea42ae1afc707cd98

test:
  secret_key_base: 48c73c37ad1912f2a66992c946db1024fd832dff64e76f54afbeb18d74093c84225fa5d778b4c37cbaa17a18dd3406a0b74dabb6074347869666741dc23cc00d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
